### ISSUE TITLE
Security report

### ISSUE THREAD

**Issue by danimesq** [pietrop/electron-video-downloader#1]
Vulnerabilities were pointed.
Please see the attached HTML file.
[electronvideodownloader-security_report.html.zip](https://github.com/pietrop/electron-video-downloader/files/3318780/electronvideodownloader-security_report.html.zip)

**Comment by danimesq** [comment]
@pietrop

**Comment by pietrop** [comment]
I don’t see any vulnerabilities in the github repo. Could you copy paste in a github comment? And where did you get those from?
