### ISSUE TITLE
Twitch not working

### ISSUE THREAD

**Issue by masudhossain** [pietrop/electron-video-downloader#5]
Using twitch links do not work, but youtube links does.

**Comment by pietrop** [comment]
👋 This module wraps around [youtube-dl](https://github.com/ytdl-org/youtube-dl). if  [youtube-dl](https://github.com/ytdl-org/youtube-dl) can handle twitch then it should work here too. If it doesn't then it's worth raising this issue in their repo at [youtube-dl](https://github.com/ytdl-org/youtube-dl). 

Closing here for now, but happy to re-open if you find out something new.
